spring:
  datasource:
    url: jdbc:mysql://localhost:3306/risk_management?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: dragon4369
    driver-class-name: com.mysql.cj.jdbc.Driver